'use client'

import './globals.css'
import type { Metadata } from 'next'
import Header from './components/header/Header'
import EntryProvider from './context/EntryProvider'
import "@fortawesome/fontawesome-svg-core/styles.css";
import { config } from "@fortawesome/fontawesome-svg-core";
import React from 'react'
import Link from 'next/link'

config.autoAddCss = false;


export const metadata: Metadata = {
  title: 'my palette',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <Header />
        <EntryProvider >
          <Link href="/week">THE FUCKING WEEK</Link>
          {children}
        </EntryProvider>
      </body>
    </html>
  )
}
